# Copy this file to app.toml and update values as appropriate.

[server]
homeserver_name = "chat.spelt.io"
identity_server = "https://id.spelt.io"
bind_address = "localhost"
port = 8080

[jwt]
issuer = "https://chat.spelt.io"

[database.dev]
host = "localhost"
port = 8000
username = "spelt_app"
password = "my-secret"
namespace = "spelt"
database_name = "dev"

[database.test]
host = "localhost"
port = 8000
username = "spelt_app"
password = "my-secret"
# The tests create randomly named databases within the specified namespace.
namespace = "spelt"
