# Copy this file to app.toml and update values as appropriate.

[server]
base_url = "https://chat.spelt.io"
identity_server = "https://id.spelt.io"
bind_address = "localhost"
port = 8080

[jwt]
issuer = "https://chat.spelt.io"

[database]
dev_uri = "postgres://dev_user:password@localhost/dev"
test_uri = "postgres://test_user:password@localhost/test"
