name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: mysecret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Configure
      run: |
        cd config &&
        openssl genpkey -outform pem -algorithm rsa -out pkey.pem &&
        openssl rsa -in pkey.pem -pubout -out public.pem &&
        cp app.ci.toml app.toml
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
      env:
        DATABASE_URL: postgres://postgres:mysecret@localhost/postgres
    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgres://postgres:mysecret@localhost/postgres
