name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
        cd config &&
        openssl genpkey -outform pem -algorithm rsa -out pkey.pem &&
        openssl rsa -in pkey.pem -pubout -out public.pem
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
